{% set name = "perl-proc-fork" %}
{% set version = "0.808" %}
{% set sha256 = "3f68c1a2978f05df229a608e95e91f4aaf834e840d588215644d8f9669ff99ce" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/A/AR/ARISTOTLE/Proc-Fork-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-exporter-tidy
  run:
    - perl
    - perl-exporter-tidy

test:
  imports:
    - Proc::Fork

about:
  home: https://metacpan.org/dist/Proc-Fork
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  summary: simple, intuitive interface to the fork() system call
  license_file:
    - {{ environ["PREFIX"] }}/man/man1/perlartistic.1
    - {{ environ["PREFIX"] }}/man/man1/perlgpl.1

extra:
  recipe-maintainers:
    - cbrueffer
